### ISSUE TITLE
Mybatis取Oracle数据库中LONG类型的字段报错

### ISSUE THREAD

**Issue by zhuangjinxin** [zhuangjinxin/question#2]
数据库表结构：

|ID |COLUMU_NAME|DATA_TYPE|NULLABLE|DATA_DEFAULT|COLUMN_ID|COMMENTS|
|---|---|---|---|---|---|---|
|1|ID|VARCHAR2(4 BYTE)|No|(null)|1|(null)|
|2|TEXT|LONG|Yes|(null)|2|(null)|

MyBatis sqlmap的写法：
```
<resultMap type="java.util.HashMap" id="LongMap">
	<result column="ID"   jdbcType="INTEGER"/>
	<result column="TEXT"  jdbcType="VARCHAR"/>
</resultMap>

<select id="testLong" resultMap="LongMap">
	select ID,TEXT from TEST_LONG where ID='1'
</select>
```

报错信息：Caused by: java.sql.SQLException: Invalid column type: getCLOB not implemented for class oracle.jdbc.driver.T4CLongAccessor

详细信息：
```
Caused by: java.sql.SQLException: Invalid column type: getCLOB not implemented for class oracle.jdbc.driver.T4CLongAccessor
	at oracle.jdbc.driver.Accessor.unimpl(Accessor.java:414) ~[ojdbc6-11.2.0.4.jar:11.2.0.4.0]
	at oracle.jdbc.driver.Accessor.getCLOB(Accessor.java:1298) ~[ojdbc6-11.2.0.4.jar:11.2.0.4.0]
	at oracle.jdbc.driver.OracleResultSetImpl.getCLOB(OracleResultSetImpl.java:1719) ~[ojdbc6-11.2.0.4.jar:11.2.0.4.0]
	at oracle.jdbc.driver.OracleResultSetImpl.getClob(OracleResultSetImpl.java:732) ~[ojdbc6-11.2.0.4.jar:11.2.0.4.0]
	at oracle.jdbc.driver.OracleResultSet.getClob(OracleResultSet.java:408) ~[ojdbc6-11.2.0.4.jar:11.2.0.4.0]
	at org.apache.ibatis.type.ClobTypeHandler.getNullableResult(ClobTypeHandler.java:38) ~[mybatis-3.2.2.jar:3.2.2]
	at org.apache.ibatis.type.ClobTypeHandler.getNullableResult(ClobTypeHandler.java:25) ~[mybatis-3.2.2.jar:3.2.2]
	at org.apache.ibatis.type.BaseTypeHandler.getResult(BaseTypeHandler.java:51) ~[mybatis-3.2.2.jar:3.2.2]
	at org.apache.ibatis.type.UnknownTypeHandler.getNullableResult(UnknownTypeHandler.java:49) ~[mybatis-3.2.2.jar:3.2.2]
	at org.apache.ibatis.type.BaseTypeHandler.getResult(BaseTypeHandler.java:51) ~[mybatis-3.2.2.jar:3.2.2]
	at org.apache.ibatis.executor.resultset.FastResultSetHandler.getPropertyMappingValue(FastResultSetHandler.java:325) ~[mybatis-3.2.2.jar:3.2.2]
	at org.apache.ibatis.executor.resultset.FastResultSetHandler.applyPropertyMappings(FastResultSetHandler.java:301) ~[mybatis-3.2.2.jar:3.2.2]
	at org.apache.ibatis.executor.resultset.FastResultSetHandler.getRowValue(FastResultSetHandler.java:270) ~[mybatis-3.2.2.jar:3.2.2]
	at org.apache.ibatis.executor.resultset.FastResultSetHandler.handleRowValues(FastResultSetHandler.java:216) ~[mybatis-3.2.2.jar:3.2.2]
	at org.apache.ibatis.executor.resultset.FastResultSetHandler.handleResultSet(FastResultSetHandler.java:188) ~[mybatis-3.2.2.jar:3.2.2]
	at org.apache.ibatis.executor.resultset.FastResultSetHandler.handleResultSets(FastResultSetHandler.java:154) ~[mybatis-3.2.2.jar:3.2.2]
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:57) ~[mybatis-3.2.2.jar:3.2.2]
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:70) ~[mybatis-3.2.2.jar:3.2.2]
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:57) ~[mybatis-3.2.2.jar:3.2.2]
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:259) ~[mybatis-3.2.2.jar:3.2.2]
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:132) ~[mybatis-3.2.2.jar:3.2.2]
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:105) ~[mybatis-3.2.2.jar:3.2.2]
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:81) ~[mybatis-3.2.2.jar:3.2.2]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:104) ~[mybatis-3.2.2.jar:3.2.2]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:98) ~[mybatis-3.2.2.jar:3.2.2]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:62) ~[mybatis-3.2.2.jar:3.2.2]
```

**Comment by zhuangjinxin** [comment]
MyBatis官网给出的解决办法：

##### Oracle LONG Datatype
The Oracle JDBC driver will report that a LONG column is JDBC type LONGVARCHAR. MyBatis will map LONGVARCHAR to CLOB which is unsupported by the Oracle driver. So, when using LONG datatype, you should do a column override in the generator to map it to VARCHAR JDBC type.

链接：`http://www.mybatis.org/generator/usage/oracle.html`

**Comment by zhuangjinxin** [comment]
其他解决办法：
The "solution" was mapping LONG as VARCHAR and disabling logging.

链接：`http://mybatis-user.963551.n3.nabble.com/Problem-mapping-Oracle-LONG-td4026299.html`

**Comment by zhuangjinxin** [comment]
最终解决办法：
使用**javaType="java.lang.String" jdbcType="VARCHAR"**，转化成字符串处理

```
<resultMap type="java.util.HashMap" id="LongMap">
	<result column="ID"   jdbcType="INTEGER"/>
	<result column="TEXT" javaType="java.lang.String" jdbcType="VARCHAR"/>
</resultMap>

<select id="testLong" resultMap="LongMap">
	select ID,TEXT from TEST_LONG where ID='1'
</select>
```
备注：使用的Oracle的JDBC驱动的版本是`11.2.0.4`,MyBatis的版本是`3.2.2`
